spring:
  datasource:
    url: jdbc:h2:mem:bili_agent;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
